workspace 'ExportToCalendar-workspace'
xcodeproj 'ExportToCalendar.xcodeproj'

platform :ios, '8.0'
use_frameworks!
link_with 'ExportToCalendar', 'ExportToCalendarTests'


pod 'EKEventStoreWrapper', :git => 'https://github.com/bphenriques/EKEventStoreWrapper.git', :tag => '0.9.11'
