workspace 'ExportToCalendar-workspace'
xcodeproj 'ExportToCalendar.xcodeproj'
platform :ios, '8.0'
use_frameworks!

def pods
    pod 'EKEventStoreWrapper'
end
 
target 'ExportToCalendar' do
    pods
end